ignore:
  resource_names:
    - AccessKey
    - AccountAlias
    - Doc
    - Group
    - LoginProfile
    - OpenIDConnectProvider
    - Policy
    - PolicyVersion
    - Role
    - SAMLProvider
    - ServiceLinkedRole
    - ServiceSpecificCredential
    - User
    - VirtualMFADevice
